name: Feature Request
description: Propose an enhancement or new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches did you think about?
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope and Impact
      description: What parts of the system would this feature affect?
      placeholder: |
        - Frontend/Backend/Both
        - Which components or modules?
        - Backward compatibility concerns?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature relate to?
      options:
        - Frontend - UI/UX
        - Backend - API
        - Backend - Preprocessing
        - Backend - UNet Segmentation
        - Backend - ViT Classification
        - Documentation
        - DevOps/Infrastructure
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking current work
        - High - Would significantly improve workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Potential Risks or Challenges
      description: Are there any risks or challenges associated with implementing this feature?
      placeholder: Technical challenges, dependencies, breaking changes...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have ideas on how to implement this, please share
      placeholder: Technical approach, libraries to use, etc...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been proposed before
          required: true
        - label: I have provided a clear description of the problem and proposed solution
          required: true
        - label: This feature aligns with the project's goals and scope
          required: false
        - label: I am willing to help implement this feature
          required: false
